"""
Business Evidence capability (Business Proof 1 and 2).

FIXTURES ARE SYNTHETIC. Every image built here is generated by the helpers
below -- drawn shapes, and EXIF written by this test. They are engineering
regression fixtures, not production samples, and passing against them says
the code paths behave, not that the capability is validated against real
field-visit photography.

The real dataset (phone photos of shop fronts and interiors, roughly half
carrying EXIF GPS and the rest with a burned-in GPS Map Camera overlay) is
not in the repository. Where a real-sample directory is dropped in at
samples/business_proof/, the marked test at the bottom picks it up.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from app.agents.business_evidence.schemas import (
    BusinessProofSlot,
    Decision,
    EvidenceKind,
    MetadataSource,
    ReasonCode,
)
from app.agents.business_evidence.service import (
    analyze_business_evidence,
    assess_quality,
    read_exif,
)

REAL_SAMPLES = Path("samples/business_proof")


# ==========================================================================
# SYNTHETIC FIXTURE BUILDERS
# ==========================================================================


def synthetic_photo(
    path: Path,
    size: tuple[int, int] = (1280, 960),
    *,
    detail: bool = True,
    dark: bool = False,
) -> Path:
    """
    A SYNTHETIC stand-in for a premises photograph.

    `detail` draws high-frequency structure so the blur measure has something
    to find; without it the image is a flat wash and reads as out of focus,
    which is how the blurred-input case is produced.
    """
    from PIL import Image, ImageDraw

    base = 30 if dark else 210
    image = Image.new("RGB", size, (base, base, base))
    draw = ImageDraw.Draw(image)

    if detail:
        step = 24
        ink = (10, 10, 10) if not dark else (90, 90, 90)
        for x in range(0, size[0], step):
            draw.line([(x, 0), (x, size[1])], fill=ink, width=3)
        for y in range(0, size[1], step):
            draw.line([(0, y), (size[0], y)], fill=ink, width=3)

    image.save(path, "JPEG", quality=92)
    return path


def with_exif_gps(
    path: Path,
    latitude: float = 26.866553,
    longitude: float = 84.643202,
    when: str = "2026:03:06 10:16:00",
    make: str = "SyntheticPhone",
) -> Path:
    """
    Write a SYNTHETIC EXIF GPS + timestamp header onto an image.

    Written with Pillow rather than a dedicated EXIF library so the test
    suite does not pull in a dependency that only fixtures would use.
    """
    from PIL import Image

    def to_dms(value: float) -> tuple[float, float, float]:
        value = abs(value)
        degrees = int(value)
        minutes_float = (value - degrees) * 60
        minutes = int(minutes_float)
        return (float(degrees), float(minutes), (minutes_float - minutes) * 60)

    with Image.open(path) as image:
        exif = image.getexif()
        exif[271] = make            # Make
        exif[272] = "Model-X"       # Model
        exif[306] = when            # DateTime

        gps = exif.get_ifd(0x8825)
        gps[1] = "N" if latitude >= 0 else "S"
        gps[2] = to_dms(latitude)
        gps[3] = "E" if longitude >= 0 else "W"
        gps[4] = to_dms(longitude)

        image.save(path, "JPEG", exif=exif, quality=92)

    return path


@pytest.fixture
def photo(tmp_path):
    """A clean SYNTHETIC premises photo with no metadata."""
    return synthetic_photo(tmp_path / "shop.jpg")


@pytest.fixture
def geotagged(tmp_path):
    """A SYNTHETIC premises photo carrying EXIF GPS and a timestamp."""
    # Pillow writes the synthetic EXIF; no extra dependency needed.
    return with_exif_gps(synthetic_photo(tmp_path / "geo.jpg"))


# ==========================================================================
# ONE CAPABILITY, BOTH SLOTS
# ==========================================================================


@pytest.mark.parametrize(
    "slot",
    [BusinessProofSlot.BUSINESS_PROOF_1, BusinessProofSlot.BUSINESS_PROOF_2],
)
def test_both_proof_slots_run_through_one_capability(geotagged, slot):
    """
    Proof 1 and Proof 2 are the same evidence class in two form slots.

    The slot is carried through as a label; it must not change how the
    evidence is judged, or the two slots have quietly become two agents.
    """
    outcome = analyze_business_evidence(str(geotagged), slot, source_id="bp")

    assert outcome.document_type is slot
    assert outcome.capability == "business_evidence"
    assert outcome.decision is Decision.PASS


def test_the_two_slots_reach_identical_verdicts_on_identical_evidence(geotagged):
    first = analyze_business_evidence(
        str(geotagged), BusinessProofSlot.BUSINESS_PROOF_1, source_id="bp"
    )
    second = analyze_business_evidence(
        str(geotagged), BusinessProofSlot.BUSINESS_PROOF_2, source_id="bp"
    )

    assert first.decision == second.decision
    assert first.checks == second.checks
    assert first.fields == second.fields


# ==========================================================================
# EXIF
# ==========================================================================


def test_exif_gps_is_read_without_ocr(geotagged, monkeypatch):
    """
    The EXIF path must not touch OCR.

    A photo with intact metadata is the common case and has to stay cheap;
    if it silently fell through to OCR the latency budget would go with it.
    """
    from app.agents.business_evidence import service

    def explode(*args, **kwargs):
        raise AssertionError("EXIF path must not invoke overlay OCR")

    monkeypatch.setattr(service, "read_overlay", explode)

    outcome = service.analyze_business_evidence(
        str(geotagged), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.metadata_source is MetadataSource.EXIF
    assert outcome.fields["latitude"] == pytest.approx(26.866553, abs=1e-4)
    assert outcome.fields["longitude"] == pytest.approx(84.643202, abs=1e-4)
    assert ReasonCode.GEOTAG_PRESENT in outcome.reason_codes


def test_southern_and_western_hemispheres_are_signed(tmp_path):
    # Pillow writes the synthetic EXIF; no extra dependency needed.
    path = with_exif_gps(
        synthetic_photo(tmp_path / "s.jpg"), latitude=-33.9, longitude=-70.6
    )

    data = read_exif(path)

    assert data["latitude"] < 0
    assert data["longitude"] < 0


def test_device_metadata_is_reported_when_present(geotagged):
    outcome = analyze_business_evidence(
        str(geotagged), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.fields["device_make"] == "SyntheticPhone"
    assert ReasonCode.DEVICE_METADATA_PRESENT in outcome.reason_codes


# ==========================================================================
# MISSING / STRIPPED METADATA
# ==========================================================================


def test_a_photo_with_no_metadata_is_review_not_pass(photo, monkeypatch):
    """
    Half the real dataset has been through something that strips EXIF.

    That is not grounds to reject the evidence, and not grounds to accept it
    unseen either -- it goes to a human.
    """
    from app.agents.business_evidence import service

    monkeypatch.setattr(service, "read_overlay", lambda path: {})

    outcome = service.analyze_business_evidence(
        str(photo), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.decision is Decision.REVIEW
    assert outcome.metadata_source is MetadataSource.NONE
    assert ReasonCode.GEOTAG_MISSING in outcome.reason_codes
    assert ReasonCode.METADATA_STRIPPED in outcome.reason_codes


def test_the_overlay_fallback_runs_only_when_exif_is_absent(photo, monkeypatch):
    """A stripped photo may still carry a burned-in GPS Map Camera caption."""
    from app.agents.business_evidence import service

    monkeypatch.setattr(
        service,
        "read_overlay",
        lambda path: {
            "latitude": 26.8665,
            "longitude": 84.6432,
            "captured_at": "06/03/2026 10:16",
            "address": "Pipra Dube, Bihar 845454, India",
        },
    )

    outcome = service.analyze_business_evidence(
        str(photo), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.metadata_source is MetadataSource.OVERLAY_OCR
    assert outcome.decision is Decision.PASS
    assert outcome.fields["address"].startswith("Pipra Dube")


def test_overlay_ocr_can_be_switched_off(photo, monkeypatch):
    monkeypatch.setenv("BUSINESS_EVIDENCE_OVERLAY_OCR", "false")

    from app.agents.business_evidence import service

    def explode(*args, **kwargs):
        raise AssertionError("overlay OCR ran while disabled")

    monkeypatch.setattr(service, "read_overlay", explode)

    outcome = service.analyze_business_evidence(
        str(photo), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.decision is Decision.REVIEW


def test_invalid_coordinates_are_rejected_not_reported(tmp_path, monkeypatch):
    """A latitude of 999 is corrupt metadata, not a location."""
    from app.agents.business_evidence import service

    path = synthetic_photo(tmp_path / "bad.jpg")
    monkeypatch.setattr(
        service,
        "read_overlay",
        lambda p: {"latitude": 999.0, "longitude": 84.6, "captured_at": "x"},
    )

    outcome = service.analyze_business_evidence(
        str(path), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert ReasonCode.GEOTAG_INVALID in outcome.reason_codes
    assert outcome.decision is Decision.REVIEW


# ==========================================================================
# QUALITY
# ==========================================================================


def test_a_tiny_image_is_flagged(tmp_path):
    path = synthetic_photo(tmp_path / "small.jpg", size=(120, 90))

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert ReasonCode.IMAGE_TOO_SMALL in outcome.reason_codes
    assert outcome.decision is Decision.REVIEW


def test_a_flat_image_reads_as_out_of_focus(tmp_path):
    path = synthetic_photo(tmp_path / "flat.jpg", detail=False)

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert ReasonCode.IMAGE_BLURRED in outcome.reason_codes
    assert outcome.decision is Decision.REVIEW


def test_a_dark_image_is_flagged(tmp_path):
    path = synthetic_photo(tmp_path / "dark.jpg", dark=True, detail=False)

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert ReasonCode.IMAGE_TOO_DARK in outcome.reason_codes


def test_poor_quality_cannot_pass_even_with_perfect_metadata(tmp_path):
    """Metadata describes a photo; it does not make an unusable one usable."""
    # Pillow writes the synthetic EXIF; no extra dependency needed.
    path = with_exif_gps(synthetic_photo(tmp_path / "blur.jpg", detail=False))

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert outcome.decision is Decision.REVIEW


def test_a_tall_image_is_recognised_as_a_collage(tmp_path):
    """The real dataset includes contact sheets of several visit photos."""
    path = synthetic_photo(tmp_path / "collage.jpg", size=(1213, 1600))

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert outcome.evidence_kind is EvidenceKind.PHOTO_COLLAGE


# ==========================================================================
# UNSUPPORTED AND INVALID INPUT
# ==========================================================================


def test_a_pdf_is_not_business_evidence(tmp_path):
    path = tmp_path / "doc.pdf"
    path.write_bytes(b"%PDF-1.4 not a photograph")

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert outcome.decision is Decision.FAIL
    assert ReasonCode.UNSUPPORTED_FILE_TYPE in outcome.reason_codes


def test_a_missing_file_fails_without_raising(tmp_path):
    outcome = analyze_business_evidence(
        str(tmp_path / "absent.jpg"), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.decision is Decision.FAIL
    assert ReasonCode.FILE_UNREADABLE in outcome.reason_codes


def test_a_corrupt_image_fails_without_raising(tmp_path):
    path = tmp_path / "corrupt.jpg"
    path.write_bytes(b"\xff\xd8\xff\xe0 not really a jpeg")

    outcome = analyze_business_evidence(str(path), "BUSINESS_PROOF_1", source_id="bp")

    assert outcome.decision is Decision.FAIL


def test_an_unknown_slot_is_refused(photo):
    outcome = analyze_business_evidence(str(photo), "BUSINESS_PROOF_9", source_id="bp")

    assert outcome.decision is Decision.FAIL
    assert ReasonCode.UNSUPPORTED_FILE_TYPE in outcome.reason_codes


# ==========================================================================
# CLAIMS THIS CAPABILITY MUST NEVER MAKE
# ==========================================================================


def test_a_pass_never_claims_the_business_exists(geotagged):
    outcome = analyze_business_evidence(
        str(geotagged), "BUSINESS_PROOF_1", source_id="bp"
    )

    assert outcome.decision is Decision.PASS
    assert outcome.business_existence_verified is False
    assert outcome.ownership_verified is False
    assert ReasonCode.BUSINESS_EXISTENCE_NOT_ESTABLISHED in outcome.reason_codes
    assert ReasonCode.OWNERSHIP_NOT_ESTABLISHED in outcome.reason_codes


def test_evidence_refs_identify_the_file_and_its_metadata_source(geotagged):
    outcome = analyze_business_evidence(
        str(geotagged), "BUSINESS_PROOF_2", source_id="bp-9"
    )

    assert len(outcome.evidence_refs) == 1
    ref = outcome.evidence_refs[0]
    assert ref.source_id == "bp-9"
    assert ref.locator == "geo.jpg"
    assert "BUSINESS_PROOF_2" in ref.detail


def test_the_common_contract_fields_are_present(geotagged):
    outcome = analyze_business_evidence(
        str(geotagged), "BUSINESS_PROOF_1", source_id="bp", request_id="REQ-1"
    )
    payload = outcome.as_tool_payload()

    for field in (
        "request_id", "source_id", "capability", "document_type", "status",
        "decision", "fields", "checks", "confidence", "reason_codes",
        "evidence_refs", "processing_ms",
    ):
        assert field in payload, field


# ==========================================================================
# REAL SAMPLES, WHEN PRESENT
# ==========================================================================


@pytest.mark.ocr
def test_real_business_photographs_when_the_dataset_is_present():
    """
    Runs only if real field-visit photos are dropped into the repository.

    Skipped by default: the production dataset is not committed here, and a
    synthetic pass must not be mistaken for validation against real evidence.
    """
    if not REAL_SAMPLES.is_dir():
        pytest.skip("real business proof samples not present")

    images = [
        p
        for p in sorted(REAL_SAMPLES.iterdir())
        if p.suffix.lower() in {".jpg", ".jpeg", ".png"}
    ]
    if not images:
        pytest.skip("no images in samples/business_proof")

    for image in images:
        outcome = analyze_business_evidence(
            str(image), "BUSINESS_PROOF_1", source_id=image.name
        )
        assert outcome.decision in (Decision.PASS, Decision.REVIEW, Decision.FAIL)
        assert outcome.business_existence_verified is False
